import React from 'react';

export const ProdutosInicio = [
  {
    id: 1,
    foto1: 'https://img.elo7.com.br/product/main/2B2130D/chapeu-personalizado-1-figura-nome-ou-frase-chapeu-de-praia.jpg',
    foto2: 'https://img.elo7.com.br/product/main/2AEA6E0/chapeu-personalizado-1-figura-nome-ou-frase-chapeu-de-praia.jpg',
    foto3: 'https://img.elo7.com.br/product/main/2AF2C2A/chapeu-personalizado-1-figura-nome-ou-frase-chapeu-de-praia.jpg',
    titulo: 'Chapéu personalizado',
    preco: 49,
    quantidade: 1,
    descricao: 'Fazemos sob encomenda. Feito manualmente.',
    metodoPagamento: 'Cartão de crédito',
    numeroParcelas: '4',
    categoria: 'Acessórios',

  },
  {
    id: 2,
    foto1: 'https://img.elo7.com.br/product/main/1A0252B/adesivo-de-parede-infantil-vingadores-crianca.jpg',
    foto2: 'https://img.elo7.com.br/product/main/1A0252F/adesivo-de-parede-infantil-vingadores-floresta.jpg',
    foto3: 'https://img.elo7.com.br/product/main/1A02533/adesivo-de-parede-infantil-vingadores-natureza.jpg',
    titulo: 'Adesivo de parede',
    preco: 10,
    quantidade: 1,
    descricao: 'Adesivo para parede infantil.',
    metodoPagamento: 'Boleto',
    numeroParcelas: '2',
    categoria: 'Acessórios',
  },
  {
    id: 3,
    foto1: 'https://img.elo7.com.br/product/zoom/2DBABFD/par-de-brincos-de-pressao-festa-festa.jpg',
    foto2: 'https://img.elo7.com.br/product/zoom/2DBABFE/par-de-brincos-de-pressao-festa-longo.jpg',
    foto3: 'https://img.elo7.com.br/product/zoom/2DBABFF/par-de-brincos-de-pressao-festa-brincos-de-pressao.jpg',
    titulo: 'Brincos de strass',
    preco: 50,
    quantidade: 1,
    descricao: 'Brinco em bijuteria prata.',
    metodoPagamento: 'Cartão de crédito',
    numeroParcelas: '5',
    categoria: 'Bijuteria',
  },
  {
    id: 4,
    foto1: 'https://img.elo7.com.br/product/main/1B0FDE2/robe-em-cetim-personalizado.jpg',
    foto2: 'https://img.elo7.com.br/product/main/2805696/robe-em-cetim-personalizado-promocao.jpg',
    foto3: 'https://img.elo7.com.br/product/main/2C78C7C/robe-em-cetim-personalizado-promocao.jpg',
    titulo: 'Robe de cetim',
    preco: 21,
    quantidade: 1,
    descricao: 'Robe em cetim personalizado com nome bordado.',
    metodoPagamento: 'Boleto',
    numeroParcelas: '2',
    categoria: 'Casamento',
  },
  {
    id: 5,
    foto1: 'https://img.elo7.com.br/product/main/1DD63A0/semana-maluca-convite-de-casamento-r-0-79-convite-com-strass.jpg',
    foto2: 'https://img.elo7.com.br/product/main/1DD639E/semana-maluca-convite-de-casamento-r-0-79-meia-perola.jpg',
    foto3: 'https://img.elo7.com.br/product/main/2EAC041/promocao-convite-de-casamento.jpg',
    titulo: 'Convite de casamento',
    preco: 33,
    quantidade: 1,
    descricao: 'Personalizamos todos os textos do convite!',
    metodoPagamento: 'Cartão de crédito',
    numeroParcelas: '5',
    categoria: 'Casamento',
  },
  {
    id: 6,
    foto1: 'https://img.elo7.com.br/product/main/2C43D8C/botton-lgbtq.jpg',
    foto2: 'https://img.elo7.com.br/product/main/2C43DBE/botton-lgbtq-stonewall-50-anos.jpg',
    foto3: 'https://img.elo7.com.br/product/main/30B0F2F/botton-lgbtq-marrom-e-preto-e-trans-roupas.jpg',
    titulo: 'Botton LGBTQ+',
    preco: 4,
    quantidade: 1,
    descricao: 'Prensado sobre uma base de alumínio ou flandres = maior resistência.',
    metodoPagamento: 'Boleto',
    numeroParcelas: '1',
    categoria: 'Acessórios',
  },
  {
    id: 7,
    foto1: 'https://img.elo7.com.br/product/zoom/21C15A0/fantasia-minions-presente.jpg',
    foto2: 'https://img.elo7.com.br/product/zoom/288447F/fantasia-infantil-minions-curto.jpg',
    foto3: 'https://img.elo7.com.br/product/zoom/2933C5D/fantasia-mulher-maravilha-infantil.jpg',
    titulo: 'Fantasia Minion',
    preco: 110,
    quantidade: 1,
    descricao: 'Deixe uma criança muito feliz e não perca esta oportunidade.',
    metodoPagamento: 'Cartão de débito',
    numeroParcelas: '10',
    categoria: 'Infantil',
  },
  {
    id: 8,
    foto1: 'https://img.elo7.com.br/product/main/21810CA/presepio-em-gesso-15-pecas-20-cm.jpg',
    foto2: 'https://img.elo7.com.br/product/main/21810C7/presepio-em-gesso-15-pecas-20-cm.jpg',
    foto3: 'https://img.elo7.com.br/product/main/21810E1/presepio-em-gesso-15-pecas-20-cm.jpg',
    titulo: 'Presépio em gesso',
    preco: 250,
    quantidade: 1,
    descricao: 'Lindo presépio em gesso pintado e decorado com pedras decorativas.',
    metodoPagamento: 'Cartão de crédito',
    numeroParcelas: '15',
    categoria: 'Religiosos',
  },
  {
    id: 9,
    foto1: 'https://img.elo7.com.br/product/zoom/A02B83/pulseira-folheado-olho-grego-festa.jpg',
    foto2: 'https://img.elo7.com.br/product/zoom/A02B84/pulseira-folheado-olho-grego-strass.jpg',
    foto3: 'https://img.elo7.com.br/product/zoom/A02B85/pulseira-folheado-olho-grego-moda.jpg',
    titulo: 'Pulseira olho grego',
    preco: 70,
    quantidade: 1,
    descricao: 'Regulável a todos os tamanhos.',
    metodoPagamento: 'Cartão de débito',
    numeroParcelas: '10',
    categoria: 'Bijuteria',
  },
  {
    id: 10,
    foto1: 'https://img.elo7.com.br/product/zoom/1F2B630/xilofone-brinquedo-de-madeira-separe-suas-tags-com-virgulas.jpg',
    foto2: 'https://img.elo7.com.br/product/zoom/1F2B631/xilofone-brinquedo-de-madeira-separe-suas-tags-com-virgulas.jpg',
    foto3: 'https://img.elo7.com.br/product/zoom/1F2B632/xilofone-brinquedo-de-madeira-separe-suas-tags-com-virgulas.jpg',
    titulo: 'Xilofone',
    preco: 50,
    quantidade: 1,
    descricao: 'Afinado em escala maior, possibilita a execução de muitas músicas',
    metodoPagamento: 'Boleto',
    numeroParcelas: '10',
    categoria: 'Infantil',
  },
  {
    id: 11,
    foto1: 'https://img.elo7.com.br/product/main/214F591/lembrancinha-personalizada-para-catequista-catequese-catequese.jpg',
    foto2: 'https://img.elo7.com.br/product/main/227A48C/tag-personalizada-em-madeira-para-lembrancinhas-suculentas-convidados.jpg',
    foto3: 'https://img.elo7.com.br/product/main/227A48B/tag-personalizada-em-madeira-para-lembrancinhas-suculentas-mdf.jpg',
    titulo: 'Lembrança',
    preco: 15,
    quantidade: 1,
    descricao: 'Corte e gravação a laser de altíssima qualidade.',
    metodoPagamento: 'Cartão de crédito',
    numeroParcelas: '2',
    categoria: 'Religiosos',
  },
  {
    id: 12,
    foto1: 'https://img.elo7.com.br/product/main/32635EC/capa-para-o-livro-vade-mecum-personalizada-tradicional.jpg',
    foto2: 'https://img.elo7.com.br/product/main/32635FA/capa-para-o-livro-vade-mecum-personalizada-tradicional.jpg',
    foto3: 'https://img.elo7.com.br/product/main/2DDA664/capa-para-o-livro-vade-mecum-personalizada-tradicional.jpg',
    titulo: 'Livro Vade Mecum',
    preco: 43,
    quantidade: 1,
    descricao: 'Feito em material sintético e impermeável.',
    metodoPagamento: 'Boleto',
    numeroParcelas: '8',
    categoria: 'Religiosos',
  },
];